set nocompatible

set cursorline
set exrc

set nu
set relativenumber

set incsearch

set noerrorbells

set tabstop=4 softtabstop=4
set expandtab
set smartindent
set ignorecase
set smartcase
set nowrap

set hidden
set noswapfile
set nobackup
set undodir='~/.vim/undodir'
set undofile

set termguicolors
set scrolloff=8
set showcmd
set showmode
set showmatch

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

set colorcolumn=80

set updatetime=10

call plug#begin('~/.vim/plugged')
Plug 'gruvbox-community/gruvbox'
call plug#end()

colorscheme gruvbox
